### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SuhailAhmad1** [ydataai/pandas-profiling#999] opened 2022-06-17 09:54 UTC
### Current Behaviour

Trying to import ProfileReport from pandas_profiling but everytime i try to import, it is showing an error message
![Screenshot (9)](https://user-images.githubusercontent.com/89300429/174274317-3c48b367-cd59-481d-b4d9-2ab2cbf79137.png)

### Expected Behaviour

It should import ProfileReport

### Data Description

My dataset is available at 'https://drive.google.com/file/d/1KjrSid8AfVggkCX3pmcpRE-OAi8CHVUr/view?usp=sharing'

### Code that reproduces the bug

```Python
import pandas as pd
from pandas_profiling import ProfileReport
```

### pandas-profiling version

v2.9.0 even tried many other versions.

### Dependencies

```Text
pandas = 1.4.1
```

### OS

Windows 11

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by SuhailAhmad1** [comment] 2022-06-17 09:56
For some versions of pandas_profiling it did import ProfileReport but while constructing the report it was showing error "join_axis"

**Comment by abhicantdraw** [comment] 2022-06-22 00:35
@SuhailAhmad1 
The problem isn't with pandas-profiling so much as it is a problem with the visions package looking for ABCIndexClass  within pandas and newer versions of pandas (>=1.3.x) have removed this reference. 

In the next build of pandas-profiling, because the visions package has been bumped up to 0.7.5, the correct reference will be picked up. 

For now, you can simply `!pip install visions==0.7.5` in your Google Collab notebook and retry importing ProfileReport from pandas-profiling.

**Comment by fabclmnt** [comment] 2022-08-23 23:17
@SuhailAhmad1 were you able to overcome your challenge?

**Comment by fabclmnt** [comment] 2022-10-02 22:54
Closing the issue as not updates were provided.

@SuhailAhmad1 feel free to let us know if it still remains and I'll be happy to re-open the discussion.

**Closed by fabclmnt** 2022-10-02 22:54 UTC
Labels: needs-triage
