### ISSUE TITLE
Cramer correlation matrix is not computed

### ISSUE THREAD

**Issue by bdao568** [ydataai/pandas-profiling#1099] opened 2022-10-06 16:21 UTC
/usr/local/lib/python3.7/dist-packages/pandas_profiling/model/correlations.py:61: UserWarning:There was an attempt to calculate the cramers correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"cramers": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/pandas-profiling/issues
(include the error message: 'No data; `observed` has size 0.')
 pls help. My dataset is https://busan302.mycourses.work/data/house_price_train.csv

**Comment by fabclmnt** [comment] 2022-10-06 16:24
> /usr/local/lib/python3.7/dist-packages/pandas_profiling/model/correlations.py:61: UserWarning:There was an attempt to calculate the cramers correlation, but this failed. To hide this warning, disable the calculation (using `df.profile_report(correlations={"cramers": {"calculate": False}})` If this is problematic for your use case, please report this as an issue: https://github.com/ydataai/pandas-profiling/issues (include the error message: 'No data; `observed` has size 0.') pls help. My dataset is https://busan302.mycourses.work/data/house_price_train.csv

Hi @bdao568 thank you for submitting your support request. 
Can you please share the `pandas-profiling` version you are using?

**Comment by bdao568** [comment] 2022-10-06 16:29
> > /usr/local/lib/python3.7/dist-packages/pandas_profiling/model/correlations.py:61: UserWarning:There was an attempt to calculate the cramers correlation, but this failed. To hide this warning, disable the calculation (using `df.profile_report(correlations={"cramers": {"calculate": False}})` If this is problematic for your use case, please report this as an issue: https://github.com/ydataai/pandas-profiling/issues (include the error message: 'No data; `observed` has size 0.') pls help. My dataset is https://busan302.mycourses.work/data/house_price_train.csv
> 
> Hi @bdao568 thank you for submitting your support request. Can you please share the `pandas-profiling` version you are using?

Im using this particular one https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

**Comment by fabclmnt** [comment] 2022-10-06 16:34
Can you please share the stack trace as well as the sample of your code?

**Comment by bdao568** [comment] 2022-10-06 16:35
> Can you please share the stack trace as well as the sample of your code?

https://colab.research.google.com/drive/1GKbCuAxNL91MN6jyNlyHn6zfnB7tcRCN?usp=sharing

**Comment by fabclmnt** [comment] 2022-10-06 16:54
Thank you! I'll take a look into it and get back to you.

**Comment by fabclmnt** [comment] 2022-10-06 17:27
@bdao568 it seems there is a bug related with Cramer's calculation for your dataset. 

I was able to generate the html report with no Cramer correlation matrix calculated. This is the workaround while we try to better understand the root cause.

**Comment by alexbarros** [comment] 2022-10-18 10:50
fixed by #1109

**Closed by alexbarros** 2022-10-18 10:50 UTC
Labels: bug 🐛
